### ISSUE TITLE
Public CI and slack channel

### ISSUE THREAD

**Issue by lilfaf** [wearefine/fae#222]
Guys you have done such an amazing job ! Guess you have found the right balance between what is managed by the gem and what remains to be developed. Great flexibility !

You should concider setting up a Circle CI or Travis account (in addition to your jenkins) and create support channel on Slack to increase popularity.

Regards

**Comment by jamesmk** [comment]
Thanks for the kind words @lilfaf! 

Re: CI, we are currently working on getting Jenkins up and running and reporting test results on each PR. We have a separate staging env for the dummy that Jenkins deploys to as well, so we would like to keep both concerns for the build there. The thing that is holding us up right now is getting Jenkins to run the tests across multiple Ruby and Rails versions, but we're close.

I'm definitely considering a Slack channel, mainly to help those getting started. My concern there is too much synchronous noise in my workday, which is why GH issues is fine with me for now. However, you may see one pop up in the next couple weeks.
