### ISSUE TITLE
Validation messages don't display properly

### ISSUE THREAD

**Issue by JuliannaGreen** [wearefine/fae#241]
When using either regex or complete validators, the label name is appended before the message. 

There are two problems with this pattern. 

1. The Message returns `null` when the field contains helper text.

2. Coercing the input label's name before the message might work for the default message that Fae returns for each validation type (ex. `Email Address is invalid`), however, if someone wants to add something like:
`Please enter a valid email address`
...returning the input label before the message will yield:
`Email Address Please enter a valid email address`

**Comment by tshedor** [comment]
@JuliannaGreen Hey Julianna. Tim here. I've been [poking around](https://github.com/joecorcoran/judge/blob/master/app/assets/javascripts/judge.js) this issue, and it's coming from Judge. It's injecting a blank space at the beginning and then the attribute name. But I can't for the life of me figure out how it's joining the array of messages or determining the attribute name. It's in this JS file because there isn't an XHR call on the attribute I'm validating.

**Comment by jamesmk** [comment]
@tshedor: @JuliannaGreen pointed out to me that it's actually Fae doing it: https://github.com/wearefine/fae/blob/master/app/assets/javascripts/fae/form/_validator.js#L140
It's grabbing the label value and prepending it to each method.

The first issue seems to be with the label selector in said method when there's helper text. The second issue, however would be hard to accomplish with our `"#{attr_name} #{error_message}"` format while maintaining backwards compatibility.

What I'm wondering is if we need to keep the attribute name in the error messages at all? What if we just drop them and easily resolve both issues? Let's bring this internal to discuss.

thanks

**Comment by jamesmk** [comment]
Moving to internal ticket
