### ISSUE TITLE
[feature request] nested lists UI for models which act_as_tree

### ISSUE THREAD

**Issue by y-chiasson** [wearefine/fae#258]
Hi, I would like to propose a faeture.

We have an `ArticleCategory` model which is implemented as a tree using the `act_as_tree` gem.
I believe it is common to want to arrange categories in a parent -> child relationship.

My proposition, is to implement something similar to the `Fae::UtilitiesController#sort` action, but call it `#sort_tree`.

I will share an example app.

**Comment by y-chiasson** [comment]
https://github.com/buysell-technologies/fae-issue-258-example-app

Here is the example app. Just clone the repository, and run the `generate_app.sh` file.
You will need to have rails 4.2.9 as your default rails installation, or it may try to generate the app
with a rails 5.0 > version and things won't work.

**Comment by y-chiasson** [comment]
after you generated the app, go to http://localhost:3000/admin/categories, create your admin, 
and start sorting and nesting the list.

**Comment by jamesmk** [comment]
We deal with this type of parent child relationship a lot. We do it by looping through the categories and displaying a header/table for each category with sorting enabled on the child index. Sorting is only scoped to the table you're editing, so that combined with a scope on you `acts_as_list` is enough for us to have a functioning and sortable parent/child relationship.

I'm hesitant to introduce a different way to do this and then have to support both methods. Maybe what we need is documentation and use cases in the dummy on the method we use?

**Comment by y-chiasson** [comment]
@jamesmk Thank you for taking the time to look into this.

 It would be greatly appreciated if you could link an example of how you guys are currently implementing it. I would prefer doing it the way it's currently done, rather than adding extra dependencies!

**Comment by jamesmk** [comment]
@y-chiasson I've added docs and an example in the dummy app of a basic parent/child relationship. Check out https://github.com/wearefine/fae/pull/269/files#diff-db90500d78b863ee9e5ea4a9cddd0a51.

Let me know if this helps.

thanks!

**Comment by y-chiasson** [comment]
@jamesmk Thank you so much for writing such a thorough example! I will try implementing it this way and let you know if I run into any issues. If it works well, I will drop the changes I made to Fae and use this instead!
