### ISSUE TITLE
Testing pages using fae content blocks

### ISSUE THREAD

**Issue by mitramejia** [wearefine/fae#340]
Given a `home_controller.rb` 

```
class HomeController < ApplicationController
  def index
    @home_page  = HomePage.instance
  end
end
```

Here's the index.html.slim file
`== render :partial => 'home/header', :locals => { title: @home_page.title, hero_image: @home_page.hero_image.asset.url }`

I'm trying to write an integration test for this `spec/features/home_spec.rb`

```
require 'rails_helper'

feature 'Site navigation' do
  scenario 'has home link' do
    visit root_path
    expect(page).to have_link('Home')
  end
end
```

When I inspect this spec with pry, `@home_page.title` is defined but `@hero_image` is `nil`. Even though the image shows correctly in localhost. How would you do integration tests to pages using fae content blocks?

**Comment by jamesmk** [comment]
Since the test will assume an reset DB, `HomePage.instance` will create a new page record and define all the page attributes as associations. The difference is `title` is a real attribute on the `Fae::StaticPage` object that will get setup automatically on `instance` call and `hero_image` is an association to will be `nil` until you add content to it.

In previous tests we've done, we setup test content on the page"
```
home_page = HomePage.instance
home_page.create_introduction(content: 'Test introduction content')
```

Hope this helps!

**Comment by mitramejia** [comment]
Great to now about the create_#{property} method! Can you share some examples of testing with fae. I'd like to learn more about how you guys do factories, model tests etc...
